entries/urls.py
from django.urls import path

from .views import (EntryListView, EntryDetailView,
                    EntryCreateView, EntryUpdateView, EntryDeleteView)

app_name = 'entries'
urlpatterns = [
    path('', EntryListView.as_view(), name='list'),
    path('entry/create/', EntryCreateView.as_view(), name='create'),
    path('entry/<int:pk>/', EntryDetailView.as_view(), name='detail'),
    path('entry/<int:pk>/update/', EntryUpdateView.as_view(), name='update'),
    path('entry/<int:pk>/delete/', EntryDeleteView.as_view(), name='delete')
]

manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('users.urls')),
    path('', include('entries.urls'))
]

users/urls.py
from django.urls import path

from users.views import SinginView, LogoutView

app_name = 'users'
urlpatterns = [
    path('signin/', SinginView.as_view(), name='signin'),
    path('logout/', LogoutView.as_view(), name='logout')
]

entries/models.py
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import pre_save
from django.db import models

from .utils import Crypto


class Entry(models.Model):
    """
    A model represesentation of the single entry that will be stored
    in the database.

    .. py:attribute:: name
       A name that will be used to identify an individual entry.

    .. py:attribute:: url
       URL of the entry.

    .. py:attribute:: login
       Login of the entry.

    .. py:attribute:: password
       An encrypted form of the password with a maximum length of 90 characters.
       NOTE: The real password length is limited to 50 characters.
    """
    name = models.CharField(_('name'), max_length=50)
    url = models.URLField(_('url'), max_length=200)
    login = models.CharField(_('login'), max_length=50)
    password = models.CharField(_('password'), max_length=90)

    class Meta:
        verbose_name = _('entry')
        verbose_name_plural = _('entries')
        ordering = ['name', 'url']

    def __str__(self):
        return f'{self.name} ({self.url})'


def pre_save_encrypt_password(sender, instance, *args, **kwargs):
    instance.password = Crypto().encrypt(instance.password)


pre_save.connect(pre_save_encrypt_password, sender=Entry)

entries/forms.py
from django.utils.translation import gettext_lazy as _
from django import forms
from .models import Entry


class EntryForm(forms.ModelForm):
    """Form representation of the single entry based on the `Entry` model."""

    class Meta:
        model = Entry
        fields = ['name', 'url', 'login', 'password']
        labels = {
            'name': _('name'), 'url': _('url'),
            'login': _('login'), 'password': _('password')
        }
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': _('name')}),
            'url': forms.URLInput(attrs={'placeholder': _('url')}),
            'login': forms.TextInput(attrs={'placeholder': _('login')}),
            'password': forms.PasswordInput(attrs={'placeholder': _('password')})
        }

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if len(password) > 50:
            raise forms.ValidationError(_('The password is too long. (max 50 characters)'))
        return password

users/forms.py
from django.utils.translation import ugettext as _
from django.contrib.auth import authenticate
from django import forms


class SigninForm(forms.Form):
    """
    Form representation of the user credentials.
    """
    username = forms.CharField(max_length=50, label=_('Username'),
                               widget=forms.TextInput(attrs={'placeholder': _('username')}))
    password = forms.CharField(max_length=50, label=_('Password'),
                               widget=forms.PasswordInput(attrs={'placeholder': _('password')}))

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if user is None:
            raise forms.ValidationError(_('Username or password incorrent.'))
        return super().clean()

entries/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import (ListView, DetailView, CreateView,
                                  UpdateView, DeleteView)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import ugettext as _
from django.urls import reverse, reverse_lazy
from django.contrib import messages

from .models import Entry
from .forms import EntryForm


class EntryListView(LoginRequiredMixin, ListView):
    """
    The entries list view. This view is used to display all entries
    from the database.
    """
    model = Entry
    context_object_name = 'entries'
    template_name = 'entries/entries_list.html'
    paginate_by = 10

    def get_queryset(self):
        try:
            query_name = self.request.GET.get('q')
            queryset = Entry.objects.filter(name__contains=query_name)
        except ValueError:
            queryset = Entry.objects.all()
        return queryset


class EntryDetailView(LoginRequiredMixin, DetailView):
    """
    The entry detail view. This view is used to display detailed informations
    about a specific entry in the database.
    """
    queryset = Entry.objects.all()
    context_object_name = 'entry'
    template_name = 'entries/entries_detail.html'


class EntryCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """
    The entry create view. This view is used to create a new entry in
    the database.
    """
    form_class = EntryForm
    template_name = 'entries/entries_create.html'
    success_url = reverse_lazy('entries:list')
    success_message = _('Entry successfully created.')


class EntryUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """
    The entry update view. This view is used to update existing entries
    in the database.
    """
    model = Entry
    form_class = EntryForm
    template_name = 'entries/entries_update.html'
    success_message = _('Entry successfully updated. (%(name)s)')

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data, name=self.object.name
        )

    def get_success_url(self):
        return reverse('entries:detail', args=[self.object.pk])


class EntryDeleteView(LoginRequiredMixin, DeleteView):
    """
    The entry delete view. This view is used to delete a specific
    entry from the database and redirect the user to the home page.
    """
    model = Entry
    template_name = 'entries/entries_delete.html'
    context_object_name = 'entry'
    success_url = reverse_lazy('entries:list')

    def delete(self, request, *args, **kwargs):
        messages.success(request, _('Entry successfully deleted.'))
        return super().delete(request, *args, **kwargs)

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth import authenticate, login, logout
from django.views.generic import FormView, RedirectView
from django.utils.translation import ugettext as _
from django.urls import reverse_lazy
from django.contrib import messages

from users.forms import SigninForm


class ForNotLoggedOnly(UserPassesTestMixin):
    def test_func(self):
        return not self.request.user.is_authenticated


class SinginView(ForNotLoggedOnly, FormView):
    """
    The users sign in view. This view provides login authorization
    for users.
    """
    template_name = 'users/users_signin.html'
    form_class = SigninForm

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)

        login(self.request, user)
        messages.success(self.request, _('Successfully logged in.'))
        return super().form_valid(form)

    def get_success_url(self):
        return self.request.GET.get('next', reverse_lazy('entries:list'))


class LogoutView(LoginRequiredMixin, RedirectView):
    """
    The users logout view. This view allows to log out of the account.
    """
    url = reverse_lazy('users:signin')
    login_url = reverse_lazy('users:signin')

    def get(self, request, *args, **kwargs):
        messages.success(request, _('Successfully logged out.'))
        logout(request)
        return super().get(request, *args, **kwargs)

common/templates/base.html
{% load static %}<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="author" content="Mateusz Furga">
    <meta name="keywords" content="web, password, password-manager">
    <meta name="theme-color" content="#fff">

    <link rel="stylesheet" type="text/css" href="{% static 'common.css' %}">

    <title>{% block title %} &middot; TeamPass{% endblock %}</title>

    {% block head %} {% endblock %}
</head>
<body>
    <nav id="navbar">
        <div class="container clear">
            <h1 class="fleft">TeamPass</h1>
            {% if user.is_authenticated %}
            <ul class="navbar-list fright">
                <li itemprop="name">{{ request.user }}</li>
                <li itemprop="name"><a itemprop="url" href="{% url 'entries:create' %}">new entry</a></li>
                <li itemprop="name"><a itemprop="url" href="{% url 'users:logout' %}">logout</a></li>
            </ul>
            {% endif %}
        </div>
    </nav>
    {% if messages %}<ul class="messages container">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>{% endif %}
    {% block content %}{% endblock %}
    <footer id="footer" class="container tcenter p20">
    </footer>
</body>
</html>

entries/templates/entries/entries_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Create a new entry {{ block.super }}{% endblock %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'entries/entries_create.css' %}">
{% endblock %}

{% block content %}
    <section id="dashboard" class="main">
        <div class="container">
            <header class="header">
                <h1 class="title">Create a new entry</h1>
            </header>
            <div class="content">
				<form action="" method="post" class="form">
					{% csrf_token %}
					{% for field in form.visible_fields %}
					<div class="row">
						<ul class="errors">
							{% if field.errors %}
							{% for error in field.errors %}
								<li>{{ error }}</li>
							{% endfor %}
							{% endif %}
						</ul>
						{{ field.label_tag }}
						{{ field }}
					</div>
					{% endfor %}
					<a onclick="showGenerator();" style="cursor: pointer;">generate password</a> |
					<a onclick="showPassword();" style="cursor: pointer;" id="show">show password</a>
					<div id="generator" class="p10" style="display: none;">
						<h4 class="p10">Simple password generator</h4>
						lowercase <input id="lowercase" type="checkbox" checked> |
						uppercase <input id="uppercase" type="checkbox"> |
						numbers <input id="numbers" type="checkbox">
						<input id="length" type="number" value="10" placeholder="characters length" style="width: 120px !important;">
						<button class="btn success" type="button" onclick="generate();">Generate</button>
					</div>
					<div class="row">
						<button class="btn warning" type="submit">Save</button>
					</div>
					<div class="p10-top">
						<a href="{% url 'entries:list' %}">&laquo; Home page</a>
					</div>
				</form>
			</div>
        </div>
	</section>
	<script>
		function showGenerator()
		{
			var gen = document.getElementById("generator");
			gen.style.display = "block";
		}

		function showPassword()
		{
			var pass = document.getElementById("id_password");
			var link = document.getElementById("show");

			if (pass.type === "password") {
				pass.type = "text";
				link.text = "hide password";
			} else {
				pass.type = "password";
				link.text = "show password";
			}
			
		}

		function generate()
		{
			var allow_lower = document.getElementById("lowercase").checked;
			var allow_upper = document.getElementById("uppercase").checked;
			var allow_numbers = document.getElementById("numbers").checked;
			var length = document.getElementById("length").value;

			var lowercase = "abcdefghijklmnopqrstuvwxyz";
			var uppercase = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
			var numbers = "0123456789";

			var possible = "";

			if (allow_lower) possible += lowercase;
			if (allow_upper) possible += uppercase;
			if (allow_numbers) possible += numbers;

			var password = "";

			if (! possible) return;

			if (window.crypto && window.crypto.getRandomValues) {
				values = new Uint32Array(length);
				window.crypto.getRandomValues(values);

				for (var i = 0; i < length; i++)
					password += possible[values[i] % possible.length];
			} else {
				for (var i = 0; i < length; i++)
					password += possible.charAt(Math.floor(Math.random() * possible.length));
			}

			var input = document.getElementById("id_password");
			input.value = password;
		}
	</script>
{% endblock %}

entries/templates/entries/entries_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Delete an entry {{ block.super }}{% endblock %}

{% block content %}
    <section id="dashboard" class="main">
        <div class="container">
            <header class="header">
                <h1 class="title">Delete an entry</h1>
            </header>
            <div class="content">
                <p>Are you sure you want to delete <strong>{{ entry.name }}</strong> entry?</p>
                <form action="" method="post">
                    {% csrf_token %}
                    <button class="btn error m10" type="submit">Delete the entry</button>
                </form>
                <a href="{% url 'entries:list' %}">Nope, take me away from here!</a>
            </div>
        </div>
    </section>
{% endblock %}

entries/templates/entries/entries_detail.html
{% extends 'base.html' %}
{% load static %}
{% load decrypt %}

{% block title %} {{ entry.name }} {{ block.super }}{% endblock %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'entries/entries_detail.css' %}">
{% endblock %}

{% block content %}
    <section id="dashboard" class="main">
        <div class="container">
            <header class="header clear">
                <h1 class="title fleft">{{ entry.name }}</h1>
                <div class="row fright">
                    <a href="{% url 'entries:update' entry.id %}"><button class="btn warning">Edit the entry</button></a>
                    <a href="{% url 'entries:delete' entry.id %}"><button class="btn error">Delete the entry</button></a>
                </div>
            </header>
            <div class="content">
                <div class="row">
                    <p>
                        <span class="title">URL:</span>
                        <a target="_blank" rel="noopener noreferrer" href="{{ entry.url }}">{{ entry.url }}</a>
                    </p>
                </div>
                <div class="row">
                    <p>
                        <span class="title">Login: </span>
                        {{ entry.login }}
                    </p>
                </div>
                <div class="row">
                    <p>
                        <span class="title">Password:</span>
                        <input style="min-width: 200px;" type="password" value="{{ entry.password | decrypt }}" id="password" disabled>
                        <a style="font-family: monospace; cursor: pointer;" id="password-button" onclick="showPassword();">show</a>
                        <a style="font-family: monospace; cursor: pointer;" onclick="copyToClipboard()">copy</a>
                    </p>
                </div>
                <div class="p10-top">
                    <a href="{% url 'entries:list' %}">&laquo; Home page</a>
                </div>
            </div>
        </div>
    </section>
    <script>
        function showPassword() {
            var input = document.getElementById("password");
            var input_button = document.getElementById("password-button");

            if (input.type === "password") {
                input.type = "text";
                input_button.text = "hide";
            } else {
                input.type = "password";
                input_button.text = "show";
            }
        }

        function copyToClipboard() {
            var password = document.getElementById("password").value;
            
            var elem = document.createElement("textarea");
            elem.value = password;
            elem.style = { position: 'absolute', left: '-9999px' };
            document.body.appendChild(elem);

            elem.select();
            document.execCommand("copy");
            document.body.removeChild(elem);
        }
    </script>
{% endblock %}

entries/templates/entries/entries_list.html
{% extends 'base.html' %}
{% load static %}
{% load decrypt %}

{% block title %} Dashboard {{ block.super }}{% endblock %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'entries/entries_list.css' %}">
{% endblock %}

{% block content %}
    <section id="dashboard" class="main">
        <div class="container">
            <header class="header">
                <h1 class="title">List of entries</h1>
                <p class="p10">number of entries: <span class="fbold">{{ entries.count }}</span></p>
            </header>
            <div class="content">
                    <div class="posts-search tcenter p20-bottom">
                        <form action="" method="get">
                            <input type="text" name="q" placeholder="search for entry" value="{{ request.GET.q }}">
                            <button class="btn warning">Search</button>
                        </form>
                    </div>
                <table>
                    <thead>
                        <tr>
                            <th>name</th>
                            <th>url</th>
                            <th>username</th>
                            <th>password</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for entry in entries %}
                        <tr>
                            <td><a href="{% url 'entries:detail' entry.id %}">{{ entry.name }}</a></td>
                            <td><a href="{{ entry.url }}" target="_blank" rel="noopener noreferrer">{{ entry.url }}</a></td>
                            <td>{{ entry.login }}</td>
                            <td class="tcenter">
                                <input id="password-{{ entry.id}}" style="width: auto;" type="password" value="{{ entry.password | decrypt}}" disabled>
                                <a style="font-family: monospace; cursor: pointer;" id="password-button-{{ entry.id }}" onclick="showPassword({{ entry.id }});">show</a>
                                <a style="font-family: monospace; cursor: pointer;" onclick="copyToClipboard({{ entry.id }})">copy</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <ul class="pagination tcenter p20-top">
                    <li class="prev">&laquo; <a {% if page_obj.has_previous %}href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"{% endif %}>Prev</a></li>
                    
					<li>{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</li>
                    
                    <li class="next"><a {% if page_obj.has_next %}href="?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% endif %}">Next</a> &raquo;</li>
				</ul>
            </div>
        </div>
    </section>
    <script>
        function showPassword(id) {
            var input = document.getElementById("password-" + id);
            var input_button = document.getElementById("password-button-" + id);

            if (input.type === "password") {
                input.type = "text";
                input_button.text = "hide";
            } else {
                input.type = "password";
                input_button.text = "show";
            }
        }

        function copyToClipboard(id) {
            var password = document.getElementById("password-" + id).value;
            
            var elem = document.createElement("textarea");
            elem.value = password;
            elem.style = { position: 'absolute', left: '-9999px' };
            document.body.appendChild(elem);

            elem.select();
            document.execCommand("copy");
            document.body.removeChild(elem);
        }
    </script>
{% endblock %}

entries/templates/entries/entries_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Update an entry {{ block.super }}{% endblock %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'entries/entries_create.css' %}">
{% endblock %}

{% block content %}
    <section id="dashboard" class="main">
        <div class="container">
            <header class="header">
                <h1 class="title">Update an entry</h1>
            </header>
            <div class="content">
				<form action="" method="post" class="form">
					{% csrf_token %}
					{% for field in form.visible_fields %}
					<div class="row">
						<ul class="errors">
							{% if field.errors %}
							{% for error in field.errors %}
								<li>{{ error }}</li>
							{% endfor %}
							{% endif %}
						</ul>
						{{ field.label_tag }}
						{{ field }}
					</div>
					{% endfor %}
					<a onclick="showGenerator();" style="cursor: pointer;">generate password</a> |
					<a onclick="showPassword();" style="cursor: pointer;" id="show">show password</a>
					<div id="generator" class="p10" style="display: none;">
						<h4 class="p10">Simple password generator</h4>
						lowercase <input id="lowercase" type="checkbox" checked> |
						uppercase <input id="uppercase" type="checkbox"> |
						numbers <input id="numbers" type="checkbox">
						<input id="length" type="number" value="10" placeholder="characters length" style="width: 120px !important;">
						<button class="btn success" type="button" onclick="generate();">Generate</button>
					</div>
					<div class="row">
						<button class="btn warning" type="submit">Update</button>
					</div>
					<div class="p10-top">
						<a href="{% url 'entries:detail' object.id %}">&laquo; Back</a>
					</div>
				</form>
			</div>
        </div>
	</section>
	<script>
		function showGenerator()
		{
			var gen = document.getElementById("generator");
			gen.style.display = "block";
		}

		function showPassword()
		{
			var pass = document.getElementById("id_password");
			var link = document.getElementById("show");

			if (pass.type === "password") {
				pass.type = "text";
				link.text = "hide password";
			} else {
				pass.type = "password";
				link.text = "show password";
			}
			
		}

		function generate()
		{
			var allow_lower = document.getElementById("lowercase").checked;
			var allow_upper = document.getElementById("uppercase").checked;
			var allow_numbers = document.getElementById("numbers").checked;
			var length = document.getElementById("length").value;

			var lowercase = "abcdefghijklmnopqrstuvwxyz";
			var uppercase = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
			var numbers = "0123456789";

			var possible = "";

			if (allow_lower) possible += lowercase;
			if (allow_upper) possible += uppercase;
			if (allow_numbers) possible += numbers;

			var password = "";

			if (! possible) return;

			if (window.crypto && window.crypto.getRandomValues) {
				values = new Uint32Array(length);
				window.crypto.getRandomValues(values);

				for (var i = 0; i < length; i++)
					password += possible[values[i] % possible.length];
			} else {
				for (var i = 0; i < length; i++)
					password += possible.charAt(Math.floor(Math.random() * possible.length));
			}

			var input = document.getElementById("id_password");
			input.value = password;
		}
	</script>
{% endblock %}

users/templates/users/users_signin.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Sign in {{ block.super }}{% endblock %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/users_signin.css' %}">
{% endblock %}

{% block content %}
<section id="signin" class="main">
        <div class="container">
            <header class="header">
                <h1 class="title">Signin</h1>
            </header>
            <div class="content">
                <form action="" method="post" class="form">
                    {% csrf_token %}

                    {% if form.errors %}
                    <ul class="errors">
                        {% for k, error in form.errors.items %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                    {% for field in form.visible_fields %}
                    <div class="row">
                        <ul class="errors">
                            {% if field.errors %}
                            {% for error in field.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                            {% endif %}
                        </ul>
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                    {% endfor %}
                    <div class="row">
                        <button class="btn warning" type="submit">Signin</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock %}